In [22]:
import numpy as np

In [5]:
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [6]:
type(mylist)

list

In [7]:
my_arr = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_arr)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.linspace(5,15,3)

array([ 5., 10., 15.])

In [22]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
np.random.randn(10)

array([ 1.10092326,  1.28188302, -0.22324402, -2.38272517,  0.07339636,
        1.75280805,  1.97435046,  0.57068999, -1.05804287,  1.66293992])

In [32]:
np.random.randint(0,100,9)

array([15, 44, 24, 62, 42, 41, 62, 39, 89])

In [40]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [39]:
np.random.rand(5)

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [41]:
np.random.seed(42)
np.random.rand(5)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864])

In [6]:
arr = np.arange(25)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [8]:
ranarr = np.random.randint(0,50,5)


In [9]:
ranarr

array([30, 35,  6, 29,  2])

In [11]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
ranarr.max()

35

In [14]:
ranarr.argmax()

1

In [16]:
arr.shape

(25,)

In [24]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [18]:
arr.shape

(25,)

In [20]:
arr.dtype

dtype('int32')

In [21]:
fl = np.array([1.2,1.3,1.4])
fl.dtype

dtype('float64')