In [3]:
import numpy as np


In [18]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [19]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr_2d[0,1]

2

In [12]:
arr = np.arange(0,11)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
copy_arr = arr.copy()

In [15]:
copy_arr[5:]=1000

In [16]:
copy_arr

array([   0,    1,    2,    3,    4, 1000, 1000, 1000, 1000, 1000, 1000])

In [17]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#Boolean

In [23]:
arr = np.arange(1,11)

In [24]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
boolean_arr = arr>4

In [27]:
boolean_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [28]:
arr[boolean_arr]

array([ 5,  6,  7,  8,  9, 10])

In [29]:
arr[arr<5]

array([1, 2, 3, 4])