In [4]:
import numpy as np

In [7]:
arr = np.arange(0,10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr/0

<ipython-input-11-39e2cbdaf753>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr/0
<ipython-input-11-39e2cbdaf753>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [12]:
0/arr

<ipython-input-12-ed13cfe22190>:1: RuntimeWarning: invalid value encountered in true_divide
  0/arr


array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [13]:
arr/arr

<ipython-input-13-50b4ced5627e>:1: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [14]:
1/arr

<ipython-input-14-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
arr/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [16]:
arr = np.arange(0,25)

In [33]:
arr.mean()
arr.std()

7.211102550927978

In [35]:
arr2d = arr.reshape(5,5)

In [36]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [38]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])